version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # Agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/Users/brade/playwright-tests:/workspace/playwright-tests  # Mount your project

volumes:
  jenkins_home: