name: Playwright Tests + Publish Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: "0 2 * * *"  # nightly run at 2AM UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 3️⃣ Install dependencies
      - run: npm ci

      # 4️⃣ Install Playwright browsers
      - run: npx playwright install --with-deps

      # 5️⃣ Run Playwright tests with HTML report
      - run: npx playwright test --reporter=html

      # 6️⃣ Deploy HTML report to GitHub Pages
      - name: Deploy Playwright Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
